apply plugin: 'com.android.library'
apply plugin: 'maven-publish'



android {
    namespace 'com.github.barteksc.pdfviewer'
    compileSdk 35

    defaultConfig {
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "3.2.0-beta.1"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}


dependencies {
    implementation 'androidx.core:core:1.16.0'
    implementation project(':PdfiumAndroid')
}

